#!/usr/bin/env node
/*
 * Sprite pipeline for SUPER OGA.
 *   1. tools/sprite-art.mjs draws every sprite into small pixel buffers.
 *   2. Each sheet is packed into an atlas and written as SVG  -> assets/svg/<sheet>.svg
 *   3. librsvg (via sharp) rasterises the SVG and saves a JPG -> assets/sprites/<sheet>.jpg
 *   4. assets/sprites/manifest.js tells the game where every frame lives.
 *
 * JPG has no transparency, so see-through pixels are painted magenta (#ff00ff).
 * Every art pixel is drawn as an 8x8 block, which lines up exactly with JPEG's
 * 8x8 DCT blocks, so compression can't smear colours across pixel edges. The game
 * samples the centre of each block and treats magenta as transparent. After
 * writing each JPG this script decodes it again and checks that round trip.
 */
import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { buildSheets } from './sprite-art.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SVG_DIR = path.join(root, 'assets/svg');
const JPG_DIR = path.join(root, 'assets/sprites');
const SCALE = 8;
const KEY_HEX = '#ff00ff';
// Same test the game uses (src/assets.js) to decide a sampled pixel is transparent.
const KEY_RADIUS = 100;

const hexToRgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
const keyDistance = (r, g, b) => Math.sqrt((255 - r) ** 2 + g ** 2 + (255 - b) ** 2);

function pack(frames) {
  // Shelf packer: tallest frames first, 1px gutter between frames.
  const entries = Object.entries(frames).sort((a, b) => b[1].h - a[1].h || b[1].w - a[1].w);
  const area = entries.reduce((sum, [, p]) => sum + (p.w + 1) * (p.h + 1), 0);
  const maxWidth = Math.max(...entries.map(([, p]) => p.w), Math.ceil(Math.sqrt(area * 1.6)));
  const placed = [];
  let x = 0;
  let y = 0;
  let shelf = 0;
  let width = 0;
  for (const [name, pix] of entries) {
    if (x > 0 && x + pix.w > maxWidth) {
      x = 0;
      y += shelf + 1;
      shelf = 0;
    }
    placed.push({ name, pix, x, y });
    x += pix.w + 1;
    shelf = Math.max(shelf, pix.h);
    width = Math.max(width, x - 1);
  }
  return { placed, width, height: y + shelf };
}

function toSvg(sheetName, width, height, placed) {
  // One <path> per colour; each horizontal run of pixels becomes a 1px-tall subpath.
  const runs = new Map();
  for (const { pix, x: ox, y: oy } of placed) {
    for (let y = 0; y < pix.h; y++) {
      let x = 0;
      while (x < pix.w) {
        const c = pix.get(x, y);
        if (!c) {
          x++;
          continue;
        }
        let end = x + 1;
        while (end < pix.w && pix.get(end, y) === c) end++;
        if (!runs.has(c)) runs.set(c, []);
        runs.get(c).push(`M${ox + x} ${oy + y}h${end - x}v1h${x - end}z`);
        x = end;
      }
    }
  }
  const paths = [...runs].map(([c, d]) => `<path fill="${c}" d="${d.join('')}"/>`).join('\n');
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width * SCALE}" height="${height * SCALE}" ` +
    `viewBox="0 0 ${width} ${height}" shape-rendering="crispEdges">\n` +
    `<title>SUPER OGA - ${sheetName} sprites (generated by tools/build-sprites.mjs)</title>\n${paths}\n</svg>\n`
  );
}

async function verifyJpg(file, width, height, placed) {
  const expected = new Array(width * height).fill(null);
  for (const { pix, x: ox, y: oy } of placed) {
    for (let y = 0; y < pix.h; y++) for (let x = 0; x < pix.w; x++) expected[(oy + y) * width + ox + x] = pix.get(x, y);
  }
  const { data, info } = await sharp(file).raw().toBuffer({ resolveWithObject: true });
  let maxError = 0;
  let keyMistakes = 0;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const i = ((y * SCALE + SCALE / 2) * info.width + x * SCALE + SCALE / 2) * info.channels;
      const [r, g, b] = [data[i], data[i + 1], data[i + 2]];
      const transparent = keyDistance(r, g, b) < KEY_RADIUS;
      const want = expected[y * width + x];
      if (!want || transparent) {
        if (!want !== transparent) keyMistakes++;
        continue;
      }
      const [wr, wg, wb] = hexToRgb(want);
      maxError = Math.max(maxError, Math.abs(r - wr), Math.abs(g - wg), Math.abs(b - wb));
    }
  }
  return { maxError, keyMistakes };
}

const sheets = buildSheets();
fs.mkdirSync(SVG_DIR, { recursive: true });
fs.mkdirSync(JPG_DIR, { recursive: true });

const manifest = { scale: SCALE, keyRadius: KEY_RADIUS, sheets: {} };
for (const [sheetName, frames] of Object.entries(sheets)) {
  for (const [name, pix] of Object.entries(frames)) {
    for (const c of pix.colors()) {
      if (!/^#[0-9a-f]{6}$/.test(c)) throw new Error(`${sheetName}/${name} has an invalid colour "${c}"`);
      if (keyDistance(...hexToRgb(c)) < KEY_RADIUS * 1.4) {
        throw new Error(`${sheetName}/${name} uses ${c}, too close to the magenta key colour`);
      }
    }
  }
  const { placed, width, height } = pack(frames);
  const svg = toSvg(sheetName, width, height, placed);
  const svgFile = path.join(SVG_DIR, `${sheetName}.svg`);
  const jpgFile = path.join(JPG_DIR, `${sheetName}.jpg`);
  fs.writeFileSync(svgFile, svg);
  await sharp(Buffer.from(svg))
    .flatten({ background: KEY_HEX })
    .jpeg({ quality: 92, chromaSubsampling: '4:4:4' })
    .toFile(jpgFile);

  const check = await verifyJpg(jpgFile, width, height, placed);
  if (check.keyMistakes > 0 || check.maxError > 16) {
    throw new Error(`${sheetName}.jpg failed round-trip check: ${JSON.stringify(check)}`);
  }
  // Stamp the URL with a hash of the file. The name on disk stays put, but the URL
  // changes whenever the art does - which is what lets a CDN cache it forever safely.
  const stamp = crypto.createHash('sha1').update(fs.readFileSync(jpgFile)).digest('hex').slice(0, 8);
  manifest.sheets[sheetName] = {
    src: `assets/sprites/${sheetName}.jpg?v=${stamp}`,
    w: width,
    h: height,
    frames: Object.fromEntries(
      placed.sort((a, b) => a.name.localeCompare(b.name)).map((p) => [p.name, [p.x, p.y, p.pix.w, p.pix.h]]),
    ),
  };
  const kb = (f) => (fs.statSync(f).size / 1024).toFixed(0);
  console.log(
    `${sheetName.padEnd(8)} ${String(placed.length).padStart(3)} frames  ${width}x${height}px art -> ` +
      `svg ${kb(svgFile)}KB, jpg ${width * SCALE}x${height * SCALE} ${kb(jpgFile)}KB ` +
      `(round trip: max colour error ${check.maxError}, key errors ${check.keyMistakes})`,
  );
}

fs.writeFileSync(
  path.join(JPG_DIR, 'manifest.js'),
  `// Generated by tools/build-sprites.mjs - do not edit by hand.\nwindow.SPRITE_ATLAS = ${JSON.stringify(manifest)};\n`,
);
console.log('wrote assets/sprites/manifest.js');
